---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - validation.redhat.com
  resources:
  - validations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - validation.redhat.com
  resources:
  - validations/finalizers
  verbs:
  - update
- apiGroups:
  - validation.redhat.com
  resources:
  - validations/status
  verbs:
  - get
  - patch
  - update
