# permissions for end users to view validations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: validation-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: validation-operator
    app.kubernetes.io/part-of: validation-operator
    app.kubernetes.io/managed-by: kustomize
  name: validation-viewer-role
rules:
- apiGroups:
  - validation.redhat.com
  resources:
  - validations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - validation.redhat.com
  resources:
  - validations/status
  verbs:
  - get
